#define DHTPIN D7
#define DHTTYPE DHT22

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64

#define WIFI_SSID "XXXXXXXXXXXXXXXXXXXXXXX"
#define WIFI_PWD "XXXXXXXXXXXXXXXXXXXXXXX"

#define DEVICE_LOGIN_NAME "XXXXXXXXXXXXXXXXXXXXXXX"
#define DEVICE_KEY "XXXXXXXXXXXXXXXXXXXXXXX"
